// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: mno_connection.sql

package database

import (
	"context"
)

const getActiveMNOConnections = `-- name: GetActiveMNOConnections :many
SELECT
    id,
    mno_id,
    protocol,
    status,
    -- SMPP Fields
    system_id,
    password,
    host,
    port,
    use_tls,
    bind_type,
    system_type,
    enquire_link_interval_secs,
    request_timeout_secs,
    connect_retry_delay_secs,
    max_window_size,
    default_data_coding,
    source_addr_ton,
    source_addr_npi,
    dest_addr_ton,
    dest_addr_npi,
    -- HTTP Fields
    http_config,
    created_at,
    updated_at
FROM mno_connections
WHERE status = 'active'
`

// Selects all connections marked as 'active' in status
func (q *Queries) GetActiveMNOConnections(ctx context.Context) ([]MnoConnection, error) {
	rows, err := q.db.Query(ctx, getActiveMNOConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MnoConnection
	for rows.Next() {
		var i MnoConnection
		if err := rows.Scan(
			&i.ID,
			&i.MnoID,
			&i.Protocol,
			&i.Status,
			&i.SystemID,
			&i.Password,
			&i.Host,
			&i.Port,
			&i.UseTls,
			&i.BindType,
			&i.SystemType,
			&i.EnquireLinkIntervalSecs,
			&i.RequestTimeoutSecs,
			&i.ConnectRetryDelaySecs,
			&i.MaxWindowSize,
			&i.DefaultDataCoding,
			&i.SourceAddrTon,
			&i.SourceAddrNpi,
			&i.DestAddrTon,
			&i.DestAddrNpi,
			&i.HttpConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
