// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type DeliveryReportsRaw struct {
	ID               int64              `json:"id"`
	MessageSegmentID *int64             `json:"messageSegmentId"`
	MnoConnectionID  int32              `json:"mnoConnectionId"`
	RawPdu           *string            `json:"rawPdu"`
	ReceivedAt       pgtype.Timestamptz `json:"receivedAt"`
	ProcessedAt      pgtype.Timestamptz `json:"processedAt"`
	ProcessingStatus string             `json:"processingStatus"`
}

type Message struct {
	ID                      int64              `json:"id"`
	ServiceProviderID       int32              `json:"serviceProviderId"`
	SpCredentialID          int32              `json:"spCredentialId"`
	ClientMessageID         *string            `json:"clientMessageId"`
	ClientRef               *string            `json:"clientRef"`
	OriginalSourceAddr      string             `json:"originalSourceAddr"`
	OriginalDestinationAddr string             `json:"originalDestinationAddr"`
	ShortMessage            string             `json:"shortMessage"`
	TotalSegments           int32              `json:"totalSegments"`
	SubmittedAt             pgtype.Timestamptz `json:"submittedAt"`
	ReceivedAt              pgtype.Timestamptz `json:"receivedAt"`
	ApprovedSenderID        *int32             `json:"approvedSenderId"`
	TemplateID              *int32             `json:"templateId"`
	RoutedMnoID             *int32             `json:"routedMnoId"`
	CurrencyCode            string             `json:"currencyCode"`
	ProcessingStatus        string             `json:"processingStatus"`
	FinalStatus             string             `json:"finalStatus"`
	ErrorCode               *string            `json:"errorCode"`
	ErrorDescription        *string            `json:"errorDescription"`
	ProcessedForQueueAt     pgtype.Timestamptz `json:"processedForQueueAt"`
	CompletedAt             pgtype.Timestamptz `json:"completedAt"`
}

type MessageSegment struct {
	ID               int64              `json:"id"`
	MessageID        int64              `json:"messageId"`
	SegmentSeqn      int32              `json:"segmentSeqn"`
	MnoMessageID     *string            `json:"mnoMessageId"`
	MnoConnectionID  *int32             `json:"mnoConnectionId"`
	SentToMnoAt      pgtype.Timestamptz `json:"sentToMnoAt"`
	DlrStatus        *string            `json:"dlrStatus"`
	DlrReceivedAt    pgtype.Timestamptz `json:"dlrReceivedAt"`
	ErrorCode        *string            `json:"errorCode"`
	ErrorDescription *string            `json:"errorDescription"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type Mno struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	CountryCode string             `json:"countryCode"`
	NetworkCode *string            `json:"networkCode"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type MnoConnection struct {
	ID         int32              `json:"id"`
	MnoID      int32              `json:"mnoId"`
	Protocol   string             `json:"protocol"`
	Status     string             `json:"status"`
	SystemID   *string            `json:"systemId"`
	Password   *string            `json:"password"`
	Host       *string            `json:"host"`
	Port       *int32             `json:"port"`
	UseTls     *bool              `json:"useTls"`
	BindType   *string            `json:"bindType"`
	HttpConfig []byte             `json:"httpConfig"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type PricingRule struct {
	ID                int32              `json:"id"`
	ServiceProviderID int32              `json:"serviceProviderId"`
	MnoID             *int32             `json:"mnoId"`
	CurrencyCode      string             `json:"currencyCode"`
	PricePerSms       decimal.Decimal    `json:"pricePerSms"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type RoutingRule struct {
	ID        int32              `json:"id"`
	Prefix    string             `json:"prefix"`
	MnoID     int32              `json:"mnoId"`
	Priority  int32              `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type SenderID struct {
	ID                int32              `json:"id"`
	ServiceProviderID int32              `json:"serviceProviderId"`
	SenderIDString    string             `json:"senderIdString"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type ServiceProvider struct {
	ID                  int32              `json:"id"`
	Name                string             `json:"name"`
	Email               string             `json:"email"`
	Status              string             `json:"status"`
	DefaultCurrencyCode string             `json:"defaultCurrencyCode"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
}

type SpCredential struct {
	ID                int32              `json:"id"`
	ServiceProviderID int32              `json:"serviceProviderId"`
	Protocol          string             `json:"protocol"`
	Status            string             `json:"status"`
	SystemID          *string            `json:"systemId"`
	PasswordHash      *string            `json:"passwordHash"`
	BindType          *string            `json:"bindType"`
	HttpConfig        []byte             `json:"httpConfig"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type Template struct {
	ID                int32              `json:"id"`
	ServiceProviderID *int32             `json:"serviceProviderId"`
	Name              string             `json:"name"`
	Content           string             `json:"content"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type Wallet struct {
	ID                   int32              `json:"id"`
	ServiceProviderID    int32              `json:"serviceProviderId"`
	CurrencyCode         string             `json:"currencyCode"`
	Balance              decimal.Decimal    `json:"balance"`
	LowBalanceThreshold  decimal.Decimal    `json:"lowBalanceThreshold"`
	LowBalanceNotifiedAt pgtype.Timestamptz `json:"lowBalanceNotifiedAt"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt            pgtype.Timestamptz `json:"updatedAt"`
}

type WalletTransaction struct {
	ID                     int64              `json:"id"`
	WalletID               int32              `json:"walletId"`
	MessageID              *int64             `json:"messageId"`
	TransactionType        string             `json:"transactionType"`
	Amount                 decimal.Decimal    `json:"amount"`
	BalanceBefore          decimal.Decimal    `json:"balanceBefore"`
	BalanceAfter           decimal.Decimal    `json:"balanceAfter"`
	Description            *string            `json:"description"`
	TransactionDate        pgtype.Timestamptz `json:"transactionDate"`
	ReferenceTransactionID *int64             `json:"referenceTransactionId"`
}
