// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type DeliveryReportsRaw struct {
	ID               int64              `json:"id"`
	MessageID        int64              `json:"messageId"`
	MnoConnectionID  int32              `json:"mnoConnectionId"`
	RawPdu           *string            `json:"rawPdu"`
	ReceivedAt       pgtype.Timestamptz `json:"receivedAt"`
	ProcessedAt      pgtype.Timestamptz `json:"processedAt"`
	ProcessingStatus string             `json:"processingStatus"`
}

type Message struct {
	ID                  int64              `json:"id"`
	ServiceProviderID   int32              `json:"serviceProviderId"`
	SmppCredentialID    int32              `json:"smppCredentialId"`
	ClientMessageID     *string            `json:"clientMessageId"`
	SenderIDUsed        string             `json:"senderIdUsed"`
	DestinationMsisdn   string             `json:"destinationMsisdn"`
	ShortMessage        string             `json:"shortMessage"`
	TemplateID          *int32             `json:"templateId"`
	ApprovedSenderID    *int32             `json:"approvedSenderId"`
	RoutedMnoID         *int32             `json:"routedMnoId"`
	CurrencyCode        *string            `json:"currencyCode"`
	TotalSegments       int32              `json:"totalSegments"`
	ClientRef           *string            `json:"clientRef"`
	SubmittedAt         pgtype.Timestamptz `json:"submittedAt"`
	ReceivedAt          pgtype.Timestamptz `json:"receivedAt"`
	ProcessedForQueueAt pgtype.Timestamptz `json:"processedForQueueAt"`
	CompletedAt         pgtype.Timestamptz `json:"completedAt"`
	ProcessingStatus    string             `json:"processingStatus"`
	SendStatus          *string            `json:"sendStatus"`
	FinalStatus         string             `json:"finalStatus"`
	ErrorCode           *int32             `json:"errorCode"`
	ErrorDescription    *string            `json:"errorDescription"`
}

type MessageSegment struct {
	ID               int64              `json:"id"`
	MessageID        int64              `json:"messageId"`
	SegmentSeqn      int32              `json:"segmentSeqn"`
	MnoMessageID     *string            `json:"mnoMessageId"`
	MnoConnectionID  *int32             `json:"mnoConnectionId"`
	SentToMnoAt      pgtype.Timestamptz `json:"sentToMnoAt"`
	DlrStatus        *string            `json:"dlrStatus"`
	DlrReceivedAt    pgtype.Timestamptz `json:"dlrReceivedAt"`
	ErrorCode        *int32             `json:"errorCode"`
	ErrorDescription *string            `json:"errorDescription"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type Mno struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	CountryCode string             `json:"countryCode"`
	NetworkCode *string            `json:"networkCode"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type MnoConnection struct {
	ID        int32              `json:"id"`
	MnoID     int32              `json:"mnoId"`
	SystemID  string             `json:"systemId"`
	Password  string             `json:"password"`
	Host      string             `json:"host"`
	Port      int32              `json:"port"`
	UseTls    bool               `json:"useTls"`
	BindType  string             `json:"bindType"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type PricingRule struct {
	ID                int32              `json:"id"`
	ServiceProviderID int32              `json:"serviceProviderId"`
	MnoID             *int32             `json:"mnoId"`
	CurrencyCode      string             `json:"currencyCode"`
	PricePerSms       decimal.Decimal    `json:"pricePerSms"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type RoutingRule struct {
	ID        int32              `json:"id"`
	Prefix    string             `json:"prefix"`
	MnoID     int32              `json:"mnoId"`
	Priority  int32              `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type SenderID struct {
	ID                int32              `json:"id"`
	ServiceProviderID int32              `json:"serviceProviderId"`
	SenderIDString    string             `json:"senderIdString"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type ServiceProvider struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type SmppCredential struct {
	ID                int32              `json:"id"`
	ServiceProviderID int32              `json:"serviceProviderId"`
	SystemID          string             `json:"systemId"`
	PasswordHash      string             `json:"passwordHash"`
	BindType          string             `json:"bindType"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type Template struct {
	ID                int32              `json:"id"`
	ServiceProviderID *int32             `json:"serviceProviderId"`
	Name              string             `json:"name"`
	Content           string             `json:"content"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
}

type Wallet struct {
	ID                   int32              `json:"id"`
	ServiceProviderID    int32              `json:"serviceProviderId"`
	CurrencyCode         string             `json:"currencyCode"`
	Balance              decimal.Decimal    `json:"balance"`
	LowBalanceThreshold  decimal.Decimal    `json:"lowBalanceThreshold"`
	LowBalanceNotifiedAt pgtype.Timestamptz `json:"lowBalanceNotifiedAt"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt            pgtype.Timestamptz `json:"updatedAt"`
}

type WalletTransaction struct {
	ID              int64              `json:"id"`
	WalletID        int32              `json:"walletId"`
	MessageID       *int64             `json:"messageId"`
	TransactionType string             `json:"transactionType"`
	Amount          decimal.Decimal    `json:"amount"`
	BalanceBefore   decimal.Decimal    `json:"balanceBefore"`
	BalanceAfter    decimal.Decimal    `json:"balanceAfter"`
	Description     *string            `json:"description"`
	TransactionDate pgtype.Timestamptz `json:"transactionDate"`
}
