// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: otp_sender_template_assignments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOtpSenderTemplateAssignments = `-- name: CountOtpSenderTemplateAssignments :one
SELECT count(*)
FROM otp_sender_template_assignments
WHERE
    ($1::INT IS NULL OR otp_alternative_sender_id = $1::INT)
AND ($2::INT IS NULL OR otp_message_template_id = $2::INT)
AND ($3::INT IS NULL OR mno_id = $3::INT)
AND ($4::VARCHAR IS NULL OR status = $4::VARCHAR)
`

type CountOtpSenderTemplateAssignmentsParams struct {
	OtpAlternativeSenderID *int32  `json:"otpAlternativeSenderId"`
	OtpMessageTemplateID   *int32  `json:"otpMessageTemplateId"`
	MnoID                  *int32  `json:"mnoId"`
	Status                 *string `json:"status"`
}

func (q *Queries) CountOtpSenderTemplateAssignments(ctx context.Context, arg CountOtpSenderTemplateAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtpSenderTemplateAssignments,
		arg.OtpAlternativeSenderID,
		arg.OtpMessageTemplateID,
		arg.MnoID,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOtpSenderTemplateAssignment = `-- name: CreateOtpSenderTemplateAssignment :one
INSERT INTO otp_sender_template_assignments (
    otp_alternative_sender_id,
    otp_message_template_id,
    mno_id,
    priority,
    status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, otp_alternative_sender_id, otp_message_template_id, mno_id, priority, status, assignment_usage_count, created_at, updated_at
`

type CreateOtpSenderTemplateAssignmentParams struct {
	OtpAlternativeSenderID int32  `json:"otpAlternativeSenderId"`
	OtpMessageTemplateID   int32  `json:"otpMessageTemplateId"`
	MnoID                  *int32 `json:"mnoId"`
	Priority               int32  `json:"priority"`
	Status                 string `json:"status"`
}

func (q *Queries) CreateOtpSenderTemplateAssignment(ctx context.Context, arg CreateOtpSenderTemplateAssignmentParams) (OtpSenderTemplateAssignment, error) {
	row := q.db.QueryRow(ctx, createOtpSenderTemplateAssignment,
		arg.OtpAlternativeSenderID,
		arg.OtpMessageTemplateID,
		arg.MnoID,
		arg.Priority,
		arg.Status,
	)
	var i OtpSenderTemplateAssignment
	err := row.Scan(
		&i.ID,
		&i.OtpAlternativeSenderID,
		&i.OtpMessageTemplateID,
		&i.MnoID,
		&i.Priority,
		&i.Status,
		&i.AssignmentUsageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOtpSenderTemplateAssignment = `-- name: DeleteOtpSenderTemplateAssignment :exec
DELETE FROM otp_sender_template_assignments WHERE id = $1
`

func (q *Queries) DeleteOtpSenderTemplateAssignment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOtpSenderTemplateAssignment, id)
	return err
}

const getActiveOtpTemplateAssignment = `-- name: GetActiveOtpTemplateAssignment :one
SELECT
    osta.id, osta.otp_alternative_sender_id, osta.otp_message_template_id, osta.mno_id, osta.priority, osta.status, osta.assignment_usage_count, osta.created_at, osta.updated_at,
    omt.content_template,
    omt.default_brand_name
FROM otp_sender_template_assignments osta
JOIN otp_message_templates omt ON osta.otp_message_template_id = omt.id
WHERE osta.otp_alternative_sender_id = $1
  AND osta.status = 'active'
  AND omt.status = 'active' -- Ensure template itself is active
  AND (osta.mno_id = $2 OR ($2 IS NULL AND osta.mno_id IS NULL)) -- Matches specific MNO or global assignment
ORDER BY osta.priority ASC, osta.id ASC -- Lower priority number is better
LIMIT 1
`

type GetActiveOtpTemplateAssignmentParams struct {
	OtpAlternativeSenderID int32  `json:"otpAlternativeSenderId"`
	MnoID                  *int32 `json:"mnoId"`
}

type GetActiveOtpTemplateAssignmentRow struct {
	ID                     int32              `json:"id"`
	OtpAlternativeSenderID int32              `json:"otpAlternativeSenderId"`
	OtpMessageTemplateID   int32              `json:"otpMessageTemplateId"`
	MnoID                  *int32             `json:"mnoId"`
	Priority               int32              `json:"priority"`
	Status                 string             `json:"status"`
	AssignmentUsageCount   int64              `json:"assignmentUsageCount"`
	CreatedAt              pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt              pgtype.Timestamptz `json:"updatedAt"`
	ContentTemplate        string             `json:"contentTemplate"`
	DefaultBrandName       *string            `json:"defaultBrandName"`
}

// Selects the highest priority active template for a given alternative sender and optionally MNO.
func (q *Queries) GetActiveOtpTemplateAssignment(ctx context.Context, arg GetActiveOtpTemplateAssignmentParams) (GetActiveOtpTemplateAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getActiveOtpTemplateAssignment, arg.OtpAlternativeSenderID, arg.MnoID)
	var i GetActiveOtpTemplateAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.OtpAlternativeSenderID,
		&i.OtpMessageTemplateID,
		&i.MnoID,
		&i.Priority,
		&i.Status,
		&i.AssignmentUsageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentTemplate,
		&i.DefaultBrandName,
	)
	return i, err
}

const getOtpSenderTemplateAssignmentByID = `-- name: GetOtpSenderTemplateAssignmentByID :one
SELECT
    osta.id, osta.otp_alternative_sender_id, osta.otp_message_template_id, osta.mno_id, osta.priority, osta.status, osta.assignment_usage_count, osta.created_at, osta.updated_at,
    oas.sender_id_string AS alternative_sender_string,
    omt.name AS template_name,
    m.name AS mno_name
FROM otp_sender_template_assignments osta
JOIN otp_alternative_senders oas ON osta.otp_alternative_sender_id = oas.id
JOIN otp_message_templates omt ON osta.otp_message_template_id = omt.id
LEFT JOIN mnos m ON osta.mno_id = m.id
WHERE osta.id = $1 LIMIT 1
`

type GetOtpSenderTemplateAssignmentByIDRow struct {
	ID                      int32              `json:"id"`
	OtpAlternativeSenderID  int32              `json:"otpAlternativeSenderId"`
	OtpMessageTemplateID    int32              `json:"otpMessageTemplateId"`
	MnoID                   *int32             `json:"mnoId"`
	Priority                int32              `json:"priority"`
	Status                  string             `json:"status"`
	AssignmentUsageCount    int64              `json:"assignmentUsageCount"`
	CreatedAt               pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt               pgtype.Timestamptz `json:"updatedAt"`
	AlternativeSenderString string             `json:"alternativeSenderString"`
	TemplateName            string             `json:"templateName"`
	MnoName                 *string            `json:"mnoName"`
}

func (q *Queries) GetOtpSenderTemplateAssignmentByID(ctx context.Context, id int32) (GetOtpSenderTemplateAssignmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getOtpSenderTemplateAssignmentByID, id)
	var i GetOtpSenderTemplateAssignmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.OtpAlternativeSenderID,
		&i.OtpMessageTemplateID,
		&i.MnoID,
		&i.Priority,
		&i.Status,
		&i.AssignmentUsageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AlternativeSenderString,
		&i.TemplateName,
		&i.MnoName,
	)
	return i, err
}

const incrementOtpAssignmentUsage = `-- name: IncrementOtpAssignmentUsage :one
UPDATE otp_sender_template_assignments
SET assignment_usage_count = assignment_usage_count + 1
WHERE id = $1
RETURNING id, assignment_usage_count
`

type IncrementOtpAssignmentUsageRow struct {
	ID                   int32 `json:"id"`
	AssignmentUsageCount int64 `json:"assignmentUsageCount"`
}

func (q *Queries) IncrementOtpAssignmentUsage(ctx context.Context, id int32) (IncrementOtpAssignmentUsageRow, error) {
	row := q.db.QueryRow(ctx, incrementOtpAssignmentUsage, id)
	var i IncrementOtpAssignmentUsageRow
	err := row.Scan(&i.ID, &i.AssignmentUsageCount)
	return i, err
}

const listOtpSenderTemplateAssignments = `-- name: ListOtpSenderTemplateAssignments :many
SELECT
    osta.id, osta.otp_alternative_sender_id, osta.otp_message_template_id, osta.mno_id, osta.priority, osta.status, osta.assignment_usage_count, osta.created_at, osta.updated_at,
    oas.sender_id_string AS alternative_sender_string,
    omt.name AS template_name,
    m.name AS mno_name
FROM otp_sender_template_assignments osta
JOIN otp_alternative_senders oas ON osta.otp_alternative_sender_id = oas.id
JOIN otp_message_templates omt ON osta.otp_message_template_id = omt.id
LEFT JOIN mnos m ON osta.mno_id = m.id
WHERE
    ($1::INT IS NULL OR osta.otp_alternative_sender_id = $1::INT)
AND ($2::INT IS NULL OR osta.otp_message_template_id = $2::INT)
AND ($3::INT IS NULL OR osta.mno_id = $3::INT)
AND ($4::VARCHAR IS NULL OR osta.status = $4::VARCHAR)
ORDER BY osta.priority ASC, osta.id DESC
LIMIT $6::INT
OFFSET $5::INT
`

type ListOtpSenderTemplateAssignmentsParams struct {
	OtpAlternativeSenderID *int32  `json:"otpAlternativeSenderId"`
	OtpMessageTemplateID   *int32  `json:"otpMessageTemplateId"`
	MnoID                  *int32  `json:"mnoId"`
	Status                 *string `json:"status"`
	OffsetVal              int32   `json:"offsetVal"`
	LimitVal               int32   `json:"limitVal"`
}

type ListOtpSenderTemplateAssignmentsRow struct {
	ID                      int32              `json:"id"`
	OtpAlternativeSenderID  int32              `json:"otpAlternativeSenderId"`
	OtpMessageTemplateID    int32              `json:"otpMessageTemplateId"`
	MnoID                   *int32             `json:"mnoId"`
	Priority                int32              `json:"priority"`
	Status                  string             `json:"status"`
	AssignmentUsageCount    int64              `json:"assignmentUsageCount"`
	CreatedAt               pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt               pgtype.Timestamptz `json:"updatedAt"`
	AlternativeSenderString string             `json:"alternativeSenderString"`
	TemplateName            string             `json:"templateName"`
	MnoName                 *string            `json:"mnoName"`
}

func (q *Queries) ListOtpSenderTemplateAssignments(ctx context.Context, arg ListOtpSenderTemplateAssignmentsParams) ([]ListOtpSenderTemplateAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listOtpSenderTemplateAssignments,
		arg.OtpAlternativeSenderID,
		arg.OtpMessageTemplateID,
		arg.MnoID,
		arg.Status,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOtpSenderTemplateAssignmentsRow
	for rows.Next() {
		var i ListOtpSenderTemplateAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OtpAlternativeSenderID,
			&i.OtpMessageTemplateID,
			&i.MnoID,
			&i.Priority,
			&i.Status,
			&i.AssignmentUsageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AlternativeSenderString,
			&i.TemplateName,
			&i.MnoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOtpSenderTemplateAssignment = `-- name: UpdateOtpSenderTemplateAssignment :one
UPDATE otp_sender_template_assignments
SET
    otp_alternative_sender_id = COALESCE($1, otp_alternative_sender_id),
    otp_message_template_id = COALESCE($2, otp_message_template_id),
    mno_id = CASE
                WHEN $3::BOOLEAN = TRUE THEN NULL
                ELSE COALESCE($4, mno_id)
             END,
    priority = COALESCE($5, priority),
    status = COALESCE($6, status),
    assignment_usage_count = COALESCE($7, assignment_usage_count), -- If manual adjustment is needed
    updated_at = NOW()
WHERE id = $8
RETURNING id, otp_alternative_sender_id, otp_message_template_id, mno_id, priority, status, assignment_usage_count, created_at, updated_at
`

type UpdateOtpSenderTemplateAssignmentParams struct {
	OtpAlternativeSenderID *int32  `json:"otpAlternativeSenderId"`
	OtpMessageTemplateID   *int32  `json:"otpMessageTemplateId"`
	ClearMnoID             *bool   `json:"clearMnoId"`
	MnoID                  *int32  `json:"mnoId"`
	Priority               *int32  `json:"priority"`
	Status                 *string `json:"status"`
	AssignmentUsageCount   *int64  `json:"assignmentUsageCount"`
	ID                     int32   `json:"id"`
}

func (q *Queries) UpdateOtpSenderTemplateAssignment(ctx context.Context, arg UpdateOtpSenderTemplateAssignmentParams) (OtpSenderTemplateAssignment, error) {
	row := q.db.QueryRow(ctx, updateOtpSenderTemplateAssignment,
		arg.OtpAlternativeSenderID,
		arg.OtpMessageTemplateID,
		arg.ClearMnoID,
		arg.MnoID,
		arg.Priority,
		arg.Status,
		arg.AssignmentUsageCount,
		arg.ID,
	)
	var i OtpSenderTemplateAssignment
	err := row.Scan(
		&i.ID,
		&i.OtpAlternativeSenderID,
		&i.OtpMessageTemplateID,
		&i.MnoID,
		&i.Priority,
		&i.Status,
		&i.AssignmentUsageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
