// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: pricing.sql

package database

import (
	"context"

	"github.com/shopspring/decimal"
)

const getApplicablePrice = `-- name: GetApplicablePrice :one
SELECT price_per_sms, currency_code
FROM pricing_rules
WHERE service_provider_id = $1
  AND currency_code = $2
  AND (mno_id = $3 OR mno_id IS NULL) -- Match specific MNO or default
ORDER BY mno_id DESC NULLS LAST -- Prioritize specific MNO rule over default (NULL)
LIMIT 1
`

type GetApplicablePriceParams struct {
	ServiceProviderID int32  `json:"serviceProviderId"`
	CurrencyCode      string `json:"currencyCode"`
	MnoID             *int32 `json:"mnoId"`
}

type GetApplicablePriceRow struct {
	PricePerSms  decimal.Decimal `json:"pricePerSms"`
	CurrencyCode string          `json:"currencyCode"`
}

func (q *Queries) GetApplicablePrice(ctx context.Context, arg GetApplicablePriceParams) (GetApplicablePriceRow, error) {
	row := q.db.QueryRow(ctx, getApplicablePrice, arg.ServiceProviderID, arg.CurrencyCode, arg.MnoID)
	var i GetApplicablePriceRow
	err := row.Scan(&i.PricePerSms, &i.CurrencyCode)
	return i, err
}
