// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"context"
)

type Querier interface {
	CountMNOConnectionsByMNO(ctx context.Context, mnoID int32) (int64, error)
	CountMNOs(ctx context.Context) (int64, error)
	// Counts messages based on optional filters, joining necessary tables.
	// Only JOIN segments if filtering by mno_message_id
	CountMessageDetails(ctx context.Context, arg CountMessageDetailsParams) (int64, error)
	// Counts pricing rules for a specific Service Provider.
	CountPricingRulesBySP(ctx context.Context, serviceProviderID int32) (int64, error)
	// Counts routing rules, optionally filtered by MNO ID.
	CountRoutingRules(ctx context.Context, dollar_1 int32) (int64, error)
	// Counts credentials, optionally filtered by Service Provider ID
	CountSPCredentials(ctx context.Context, dollar_1 int32) (int64, error)
	CountServiceProviders(ctx context.Context) (int64, error)
	// Counts wallets for a specific Service Provider.
	CountWalletsBySP(ctx context.Context, serviceProviderID int32) (int64, error)
	CreateMNO(ctx context.Context, arg CreateMNOParams) (Mno, error)
	CreateMNOConnection(ctx context.Context, arg CreateMNOConnectionParams) (MnoConnection, error)
	// Creates initial segment record before sending attempt
	CreateMessageSegment(ctx context.Context, arg CreateMessageSegmentParams) (int64, error)
	CreatePricingRule(ctx context.Context, arg CreatePricingRuleParams) (PricingRule, error)
	CreateRoutingRule(ctx context.Context, arg CreateRoutingRuleParams) (RoutingRule, error)
	CreateSMPPCredential(ctx context.Context, arg CreateSMPPCredentialParams) (SpCredential, error)
	// Creates an SP credential (SMPP or HTTP)
	CreateSPCredential(ctx context.Context, arg CreateSPCredentialParams) (SpCredential, error)
	CreateServiceProvider(ctx context.Context, arg CreateServiceProviderParams) (ServiceProvider, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error)
	// Optional: Query to set MNO status to inactive instead of deleting
	DeactivateMNO(ctx context.Context, id int32) (Mno, error)
	// Consider consequences - deletes might fail if MNO is referenced by connections/rules (ON DELETE RESTRICT)
	// It might be safer to just set status to 'inactive'.
	DeleteMNO(ctx context.Context, id int32) error
	DeleteMNOConnection(ctx context.Context, id int32) error
	DeletePricingRule(ctx context.Context, id int32) error
	// Note: If updating mno_id, ensure the new MNO exists (handled by FK or check in handler)
	DeleteRoutingRule(ctx context.Context, id int32) error
	DeleteSPCredential(ctx context.Context, id int32) error
	DeleteServiceProvider(ctx context.Context, id int32) error
	// Inserts a new DLR forwarding job into the queue.
	EnqueueDLRForForwarding(ctx context.Context, arg EnqueueDLRForForwardingParams) error
	FindDebitTransactionForMessage(ctx context.Context, messageID *int64) (FindDebitTransactionForMessageRow, error)
	FindMessageByMnoMessageID(ctx context.Context, mnoMessageID *string) (FindMessageByMnoMessageIDRow, error)
	// Finds segment details based on MNO Message ID for DLR processing
	FindSegmentByMnoMessageID(ctx context.Context, mnoMessageID *string) (FindSegmentByMnoMessageIDRow, error)
	// Selects all connections marked as 'active' in status
	GetActiveMNOConnections(ctx context.Context) ([]MnoConnection, error)
	GetApplicablePrice(ctx context.Context, arg GetApplicablePriceParams) (GetApplicablePriceRow, error)
	GetApplicableRoutingRule(ctx context.Context, prefix string) (int32, error)
	// Filter by date range (inclusive)
	GetDailyReport(ctx context.Context, arg GetDailyReportParams) ([]GetDailyReportRow, error)
	GetMNOByID(ctx context.Context, id int32) (Mno, error)
	GetMNOConnectionByID(ctx context.Context, id int32) (MnoConnection, error)
	// Select fields needed by the Pricer
	GetMessageDetailsForPricing(ctx context.Context, id int64) (GetMessageDetailsForPricingRow, error)
	GetMessageDetailsForSending(ctx context.Context, id int64) (GetMessageDetailsForSendingRow, error)
	GetMessageFinalStatus(ctx context.Context, id int64) (string, error)
	GetMessageTotalSegments(ctx context.Context, id int64) (int32, error)
	GetMessagesByStatus(ctx context.Context, arg GetMessagesByStatusParams) ([]GetMessagesByStatusRow, error)
	GetMessagesToPrice(ctx context.Context, limit int32) ([]GetMessagesToPriceRow, error)
	// Selects pending DLR jobs and locks them for processing.
	GetPendingDLRsToForward(ctx context.Context, arg GetPendingDLRsToForwardParams) ([]GetPendingDLRsToForwardRow, error)
	// Join MNO Name for display
	GetPricingRuleByID(ctx context.Context, id int32) (GetPricingRuleByIDRow, error)
	// Join with MNOs to get the name for display
	GetRoutingRuleByID(ctx context.Context, id int32) (GetRoutingRuleByIDRow, error)
	// Gets SP credential based on a hashed API key for HTTP auth.
	GetSPCredentialByAPIKey(ctx context.Context, apiKeyHash *string) (GetSPCredentialByAPIKeyRow, error)
	GetSPCredentialByID(ctx context.Context, id int32) (SpCredential, error)
	// Gets SP credential based on a unique API key identifier for HTTP auth.
	GetSPCredentialByKeyIdentifier(ctx context.Context, apiKeyIdentifier *string) (GetSPCredentialByKeyIdentifierRow, error)
	GetSPCredentialBySystemID(ctx context.Context, systemID *string) (GetSPCredentialBySystemIDRow, error)
	// Optional: Prevent redundant updates
	// Select fields needed for DLR forwarding
	GetSPMessageInfoForDLR(ctx context.Context, id int64) (GetSPMessageInfoForDLRRow, error)
	// Gets all segment statuses for final status aggregation
	GetSegmentStatusesForMessage(ctx context.Context, messageID int64) ([]GetSegmentStatusesForMessageRow, error)
	GetServiceProviderByID(ctx context.Context, id int32) (ServiceProvider, error)
	GetTemplateContent(ctx context.Context, arg GetTemplateContentParams) (string, error)
	// Gets a specific wallet by its primary ID.
	GetWalletByID(ctx context.Context, id int32) (Wallet, error)
	GetWalletForUpdate(ctx context.Context, arg GetWalletForUpdateParams) (GetWalletForUpdateRow, error)
	GetWalletForUpdateByID(ctx context.Context, id int32) (Wallet, error)
	GetWalletsBelowThreshold(ctx context.Context) ([]GetWalletsBelowThresholdRow, error)
	InsertMessageIn(ctx context.Context, arg InsertMessageInParams) (int64, error)
	ListMNOConnectionsByMNO(ctx context.Context, arg ListMNOConnectionsByMNOParams) ([]MnoConnection, error)
	ListMNOs(ctx context.Context, arg ListMNOsParams) ([]Mno, error)
	// Lists detailed message information based on optional filters with pagination. Excludes message content.
	// LEFT JOIN needed for EXISTS filter below, but DISTINCT ON handles duplicates if join remains
	ListMessageDetails(ctx context.Context, arg ListMessageDetailsParams) ([]ListMessageDetailsRow, error)
	// Lists pricing rules for a specific Service Provider, paginated.
	ListPricingRulesBySP(ctx context.Context, arg ListPricingRulesBySPParams) ([]ListPricingRulesBySPRow, error)
	// Lists routing rules, optionally filtered by MNO ID, with pagination.
	ListRoutingRules(ctx context.Context, arg ListRoutingRulesParams) ([]ListRoutingRulesRow, error)
	// Lists credentials, optionally filtered by Service Provider ID
	ListSPCredentials(ctx context.Context, arg ListSPCredentialsParams) ([]SpCredential, error)
	ListServiceProviders(ctx context.Context, arg ListServiceProvidersParams) ([]ServiceProvider, error)
	// Lists wallets for a specific Service Provider, paginated.
	ListWalletsBySP(ctx context.Context, arg ListWalletsBySPParams) ([]Wallet, error)
	// Marks a job as failed for this attempt, increments attempts, and potentially sets to permanent failure.
	MarkDLRForwardingAttemptFailed(ctx context.Context, arg MarkDLRForwardingAttemptFailedParams) error
	// Marks a job as successfully completed.
	MarkDLRForwardingSuccess(ctx context.Context, id int64) error
	// Use this if the Sender.Send fails catastrophically *before* MNO gets involved,
	// or potentially as the final aggregated status if needed.
	MarkMessageSendFailed(ctx context.Context, arg MarkMessageSendFailedParams) error
	MarkMessageSent(ctx context.Context, id int64) error
	// Optional: Periodically run to unlock jobs held by dead workers.
	UnlockStaleDLRs(ctx context.Context) error
	// Check threshold and notification time
	UpdateLowBalanceNotifiedAt(ctx context.Context, id int32) error
	UpdateMNO(ctx context.Context, arg UpdateMNOParams) (Mno, error)
	UpdateMNOConnection(ctx context.Context, arg UpdateMNOConnectionParams) (MnoConnection, error)
	UpdateMessageDLRStatus(ctx context.Context, arg UpdateMessageDLRStatusParams) error
	// Updates the final aggregated status and error info
	UpdateMessageFinalStatus(ctx context.Context, arg UpdateMessageFinalStatusParams) error
	UpdateMessagePriced(ctx context.Context, arg UpdateMessagePricedParams) error
	UpdateMessageRoutingInfo(ctx context.Context, arg UpdateMessageRoutingInfoParams) error
	// Updates status after Sender.Send finishes (regardless of segment success/failure)
	UpdateMessageSendAttempted(ctx context.Context, id int64) error
	UpdateMessageValidatedRouted(ctx context.Context, arg UpdateMessageValidatedRoutedParams) error
	// Optional MNO ID filter
	UpdateRoutingRule(ctx context.Context, arg UpdateRoutingRuleParams) (RoutingRule, error)
	// Updates status, password hash, http_config for a credential.
	UpdateSPCredential(ctx context.Context, arg UpdateSPCredentialParams) (SpCredential, error)
	// Updates segment status based on received DLR
	UpdateSegmentDLR(ctx context.Context, arg UpdateSegmentDLRParams) error
	// Updates segment if MNO submission attempt failed
	UpdateSegmentSendFailed(ctx context.Context, arg UpdateSegmentSendFailedParams) error
	// Updates segment after successful MNO submission
	UpdateSegmentSent(ctx context.Context, arg UpdateSegmentSentParams) error
	// New Queries:
	UpdateServiceProvider(ctx context.Context, arg UpdateServiceProviderParams) (ServiceProvider, error)
	// Lock the row for atomic update
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error)
	ValidateSenderID(ctx context.Context, arg ValidateSenderIDParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
