// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"context"
)

type Querier interface {
	CreateMessageSegment(ctx context.Context, arg CreateMessageSegmentParams) (int64, error)
	CreateSMPPCredential(ctx context.Context, arg CreateSMPPCredentialParams) (SmppCredential, error)
	CreateServiceProvider(ctx context.Context, arg CreateServiceProviderParams) (ServiceProvider, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error)
	FindMessageByMnoMessageID(ctx context.Context, mnoMessageID *string) (FindMessageByMnoMessageIDRow, error)
	FindSegmentByMnoMessageID(ctx context.Context, mnoMessageID *string) (FindSegmentByMnoMessageIDRow, error)
	GetApplicablePrice(ctx context.Context, arg GetApplicablePriceParams) (GetApplicablePriceRow, error)
	GetApplicableRoutingRule(ctx context.Context, prefix string) (int32, error)
	GetMessageDetailsForPricing(ctx context.Context, id int64) (GetMessageDetailsForPricingRow, error)
	GetMessageDetailsForSending(ctx context.Context, id int64) (GetMessageDetailsForSendingRow, error)
	GetMessageFinalStatus(ctx context.Context, id int64) (string, error)
	GetMessageTotalSegments(ctx context.Context, id int64) (int32, error)
	GetMessagesByStatus(ctx context.Context, arg GetMessagesByStatusParams) ([]GetMessagesByStatusRow, error)
	GetMessagesToPrice(ctx context.Context, limit int32) ([]GetMessagesToPriceRow, error)
	GetMessagesToRoute(ctx context.Context, limit int32) ([]GetMessagesToRouteRow, error)
	GetMessagesToSend(ctx context.Context, limit int32) ([]GetMessagesToSendRow, error)
	GetSMPPCredentialBySystemID(ctx context.Context, systemID string) (GetSMPPCredentialBySystemIDRow, error)
	GetSegmentStatusesForMessage(ctx context.Context, messageID int64) ([]GetSegmentStatusesForMessageRow, error)
	GetServiceProviderByID(ctx context.Context, id int32) (ServiceProvider, error)
	GetTemplateContent(ctx context.Context, arg GetTemplateContentParams) (string, error)
	GetWalletForUpdate(ctx context.Context, arg GetWalletForUpdateParams) (GetWalletForUpdateRow, error)
	GetWalletsBelowThreshold(ctx context.Context) ([]GetWalletsBelowThresholdRow, error)
	InsertMessageIn(ctx context.Context, arg InsertMessageInParams) (int64, error)
	MarkMessageSendFailed(ctx context.Context, arg MarkMessageSendFailedParams) error
	MarkMessageSent(ctx context.Context, id int64) error
	// Check threshold and notification time
	UpdateLowBalanceNotifiedAt(ctx context.Context, id int32) error
	UpdateMessageDLRStatus(ctx context.Context, arg UpdateMessageDLRStatusParams) error
	UpdateMessageFinalStatus(ctx context.Context, arg UpdateMessageFinalStatusParams) error
	UpdateMessagePriced(ctx context.Context, arg UpdateMessagePricedParams) error
	UpdateMessageRoutingInfo(ctx context.Context, arg UpdateMessageRoutingInfoParams) error
	UpdateMessageValidatedRouted(ctx context.Context, arg UpdateMessageValidatedRoutedParams) error
	UpdateSegmentDLR(ctx context.Context, arg UpdateSegmentDLRParams) error
	UpdateSegmentSendFailed(ctx context.Context, arg UpdateSegmentSendFailedParams) error
	UpdateSegmentSent(ctx context.Context, arg UpdateSegmentSentParams) error
	// Lock the row for atomic update
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error)
	ValidateSenderID(ctx context.Context, arg ValidateSenderIDParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
