// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: routing_flex.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoutingGroupToSpCredential = `-- name: AssignRoutingGroupToSpCredential :one
UPDATE sp_credentials
SET routing_group_id = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, service_provider_id, protocol, status, system_id, password_hash, bind_type, api_key_hash, api_key_identifier, http_config, created_at, updated_at, routing_group_id
`

type AssignRoutingGroupToSpCredentialParams struct {
	RoutingGroupID *int32 `json:"routingGroupId"`
	SpCredentialID int32  `json:"spCredentialId"`
}

func (q *Queries) AssignRoutingGroupToSpCredential(ctx context.Context, arg AssignRoutingGroupToSpCredentialParams) (SpCredential, error) {
	row := q.db.QueryRow(ctx, assignRoutingGroupToSpCredential, arg.RoutingGroupID, arg.SpCredentialID)
	var i SpCredential
	err := row.Scan(
		&i.ID,
		&i.ServiceProviderID,
		&i.Protocol,
		&i.Status,
		&i.SystemID,
		&i.PasswordHash,
		&i.BindType,
		&i.ApiKeyHash,
		&i.ApiKeyIdentifier,
		&i.HttpConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoutingGroupID,
	)
	return i, err
}

const countMsisdnPrefixEntriesByGroup = `-- name: CountMsisdnPrefixEntriesByGroup :one
SELECT count(*)
FROM msisdn_prefix_entries
WHERE msisdn_prefix_group_id = $1
`

func (q *Queries) CountMsisdnPrefixEntriesByGroup(ctx context.Context, msisdnPrefixGroupID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countMsisdnPrefixEntriesByGroup, msisdnPrefixGroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMsisdnPrefixGroups = `-- name: CountMsisdnPrefixGroups :one
SELECT count(*) FROM msisdn_prefix_groups
`

func (q *Queries) CountMsisdnPrefixGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMsisdnPrefixGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoutingAssignmentsByRoutingGroup = `-- name: CountRoutingAssignmentsByRoutingGroup :one
SELECT count(*)
FROM routing_assignments
WHERE routing_group_id = $1
`

func (q *Queries) CountRoutingAssignmentsByRoutingGroup(ctx context.Context, routingGroupID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutingAssignmentsByRoutingGroup, routingGroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoutingGroups = `-- name: CountRoutingGroups :one
SELECT count(*) FROM routing_groups
`

func (q *Queries) CountRoutingGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutingGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMsisdnPrefixEntry = `-- name: CreateMsisdnPrefixEntry :one

INSERT INTO msisdn_prefix_entries (
    msisdn_prefix_group_id, msisdn_prefix
) VALUES (
    $1, $2
) RETURNING id, msisdn_prefix_group_id, msisdn_prefix, created_at, updated_at
`

type CreateMsisdnPrefixEntryParams struct {
	MsisdnPrefixGroupID int32  `json:"msisdnPrefixGroupId"`
	MsisdnPrefix        string `json:"msisdnPrefix"`
}

// Queries for MsisdnPrefixEntry
func (q *Queries) CreateMsisdnPrefixEntry(ctx context.Context, arg CreateMsisdnPrefixEntryParams) (MsisdnPrefixEntry, error) {
	row := q.db.QueryRow(ctx, createMsisdnPrefixEntry, arg.MsisdnPrefixGroupID, arg.MsisdnPrefix)
	var i MsisdnPrefixEntry
	err := row.Scan(
		&i.ID,
		&i.MsisdnPrefixGroupID,
		&i.MsisdnPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMsisdnPrefixGroup = `-- name: CreateMsisdnPrefixGroup :one

INSERT INTO msisdn_prefix_groups (
    name, description, reference
) VALUES (
    $1, $2, $3
) RETURNING id, name, description, reference, created_at, updated_at
`

type CreateMsisdnPrefixGroupParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Reference   *string `json:"reference"`
}

// Queries for MsisdnPrefixGroup
func (q *Queries) CreateMsisdnPrefixGroup(ctx context.Context, arg CreateMsisdnPrefixGroupParams) (MsisdnPrefixGroup, error) {
	row := q.db.QueryRow(ctx, createMsisdnPrefixGroup, arg.Name, arg.Description, arg.Reference)
	var i MsisdnPrefixGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoutingAssignment = `-- name: CreateRoutingAssignment :one

INSERT INTO routing_assignments (
    routing_group_id, msisdn_prefix_group_id, mno_id, status, priority, comment
) VALUES (
    $1, $2, $3, COALESCE($4, 'active'), COALESCE($5, 0), $6
) RETURNING id, routing_group_id, msisdn_prefix_group_id, mno_id, status, priority, comment, created_at, updated_at
`

type CreateRoutingAssignmentParams struct {
	RoutingGroupID      int32       `json:"routingGroupId"`
	MsisdnPrefixGroupID int32       `json:"msisdnPrefixGroupId"`
	MnoID               int32       `json:"mnoId"`
	Status              interface{} `json:"status"`
	Priority            interface{} `json:"priority"`
	Comment             *string     `json:"comment"`
}

// Queries for RoutingAssignment (the new routing rules)
func (q *Queries) CreateRoutingAssignment(ctx context.Context, arg CreateRoutingAssignmentParams) (RoutingAssignment, error) {
	row := q.db.QueryRow(ctx, createRoutingAssignment,
		arg.RoutingGroupID,
		arg.MsisdnPrefixGroupID,
		arg.MnoID,
		arg.Status,
		arg.Priority,
		arg.Comment,
	)
	var i RoutingAssignment
	err := row.Scan(
		&i.ID,
		&i.RoutingGroupID,
		&i.MsisdnPrefixGroupID,
		&i.MnoID,
		&i.Status,
		&i.Priority,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoutingGroup = `-- name: CreateRoutingGroup :one

INSERT INTO routing_groups (
    name, description, reference
) VALUES (
    $1, $2, $3
) RETURNING id, name, description, reference, created_at, updated_at
`

type CreateRoutingGroupParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Reference   *string `json:"reference"`
}

// Queries for RoutingGroup
func (q *Queries) CreateRoutingGroup(ctx context.Context, arg CreateRoutingGroupParams) (RoutingGroup, error) {
	row := q.db.QueryRow(ctx, createRoutingGroup, arg.Name, arg.Description, arg.Reference)
	var i RoutingGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMsisdnPrefixEntriesByGroup = `-- name: DeleteMsisdnPrefixEntriesByGroup :exec
DELETE FROM msisdn_prefix_entries WHERE msisdn_prefix_group_id = $1
`

func (q *Queries) DeleteMsisdnPrefixEntriesByGroup(ctx context.Context, msisdnPrefixGroupID int32) error {
	_, err := q.db.Exec(ctx, deleteMsisdnPrefixEntriesByGroup, msisdnPrefixGroupID)
	return err
}

const deleteMsisdnPrefixEntry = `-- name: DeleteMsisdnPrefixEntry :exec
DELETE FROM msisdn_prefix_entries WHERE id = $1
`

func (q *Queries) DeleteMsisdnPrefixEntry(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMsisdnPrefixEntry, id)
	return err
}

const deleteMsisdnPrefixGroup = `-- name: DeleteMsisdnPrefixGroup :exec
DELETE FROM msisdn_prefix_groups WHERE id = $1
`

// Note: This will fail if the group is referenced in routing_assignments due to ON DELETE RESTRICT.
// Handle this in application logic (e.g., unassign first or provide a force option).
func (q *Queries) DeleteMsisdnPrefixGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMsisdnPrefixGroup, id)
	return err
}

const deleteRoutingAssignment = `-- name: DeleteRoutingAssignment :exec
DELETE FROM routing_assignments WHERE id = $1
`

func (q *Queries) DeleteRoutingAssignment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRoutingAssignment, id)
	return err
}

const deleteRoutingGroup = `-- name: DeleteRoutingGroup :exec
DELETE FROM routing_groups WHERE id = $1
`

// Note: This will fail if the group is referenced in routing_assignments or sp_credentials.
func (q *Queries) DeleteRoutingGroup(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRoutingGroup, id)
	return err
}

const findMatchingPrefixGroupForMSISDN = `-- name: FindMatchingPrefixGroupForMSISDN :one
SELECT
    mpe.msisdn_prefix_group_id,
    mpe.msisdn_prefix AS matched_prefix
FROM msisdn_prefix_entries mpe
WHERE $1 LIKE mpe.msisdn_prefix || '%'
ORDER BY length(mpe.msisdn_prefix) DESC
LIMIT 1
`

type FindMatchingPrefixGroupForMSISDNRow struct {
	MsisdnPrefixGroupID int32  `json:"msisdnPrefixGroupId"`
	MatchedPrefix       string `json:"matchedPrefix"`
}

// Finds the msisdn_prefix_group_id for a given MSISDN by longest prefix match.
// $1: full_msisdn (e.g., '2348031234567')
func (q *Queries) FindMatchingPrefixGroupForMSISDN(ctx context.Context, msisdnPrefix string) (FindMatchingPrefixGroupForMSISDNRow, error) {
	row := q.db.QueryRow(ctx, findMatchingPrefixGroupForMSISDN, msisdnPrefix)
	var i FindMatchingPrefixGroupForMSISDNRow
	err := row.Scan(&i.MsisdnPrefixGroupID, &i.MatchedPrefix)
	return i, err
}

const getApplicableMnoForRouting = `-- name: GetApplicableMnoForRouting :one
SELECT
    ra.mno_id,
    m.name AS mno_name,
    mc.id AS mno_connection_id, -- Assuming you want the first active connection for that MNO
    mc.system_id AS mno_system_id -- Example field from mno_connections
FROM routing_assignments ra
JOIN mnos m ON ra.mno_id = m.id
LEFT JOIN mno_connections mc ON m.id = mc.mno_id AND mc.status = 'active' -- or 'bound'
WHERE ra.routing_group_id = $1
  AND ra.msisdn_prefix_group_id = $2
  AND ra.status = 'active'
ORDER BY
    ra.priority ASC, -- Routing assignment priority
    mc.priority ASC NULLS LAST, -- If you add priority to mno_connections
    mc.updated_at DESC -- Pick latest updated active connection as a tie-breaker
LIMIT 1
`

type GetApplicableMnoForRoutingParams struct {
	RoutingGroupID      int32 `json:"routingGroupId"`
	MsisdnPrefixGroupID int32 `json:"msisdnPrefixGroupId"`
}

type GetApplicableMnoForRoutingRow struct {
	MnoID           int32   `json:"mnoId"`
	MnoName         string  `json:"mnoName"`
	MnoConnectionID *int32  `json:"mnoConnectionId"`
	MnoSystemID     *string `json:"mnoSystemId"`
}

// Core routing query:
// Given a routing_group_id (from sp_credential or a default) and an msisdn_prefix_group_id (from MSISDN lookup),
// find the active MNO to route to.
// $1: routing_group_id
// $2: msisdn_prefix_group_id
func (q *Queries) GetApplicableMnoForRouting(ctx context.Context, arg GetApplicableMnoForRoutingParams) (GetApplicableMnoForRoutingRow, error) {
	row := q.db.QueryRow(ctx, getApplicableMnoForRouting, arg.RoutingGroupID, arg.MsisdnPrefixGroupID)
	var i GetApplicableMnoForRoutingRow
	err := row.Scan(
		&i.MnoID,
		&i.MnoName,
		&i.MnoConnectionID,
		&i.MnoSystemID,
	)
	return i, err
}

const getMsisdnPrefixEntryByID = `-- name: GetMsisdnPrefixEntryByID :one
SELECT id, msisdn_prefix_group_id, msisdn_prefix, created_at, updated_at FROM msisdn_prefix_entries
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMsisdnPrefixEntryByID(ctx context.Context, id int32) (MsisdnPrefixEntry, error) {
	row := q.db.QueryRow(ctx, getMsisdnPrefixEntryByID, id)
	var i MsisdnPrefixEntry
	err := row.Scan(
		&i.ID,
		&i.MsisdnPrefixGroupID,
		&i.MsisdnPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMsisdnPrefixEntryByPrefix = `-- name: GetMsisdnPrefixEntryByPrefix :one
SELECT id, msisdn_prefix_group_id, msisdn_prefix, created_at, updated_at
FROM msisdn_prefix_entries
WHERE msisdn_prefix = $1 LIMIT 1
`

func (q *Queries) GetMsisdnPrefixEntryByPrefix(ctx context.Context, msisdnPrefix string) (MsisdnPrefixEntry, error) {
	row := q.db.QueryRow(ctx, getMsisdnPrefixEntryByPrefix, msisdnPrefix)
	var i MsisdnPrefixEntry
	err := row.Scan(
		&i.ID,
		&i.MsisdnPrefixGroupID,
		&i.MsisdnPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMsisdnPrefixGroupByID = `-- name: GetMsisdnPrefixGroupByID :one
SELECT id, name, description, reference, created_at, updated_at FROM msisdn_prefix_groups
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMsisdnPrefixGroupByID(ctx context.Context, id int32) (MsisdnPrefixGroup, error) {
	row := q.db.QueryRow(ctx, getMsisdnPrefixGroupByID, id)
	var i MsisdnPrefixGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMsisdnPrefixGroupByReference = `-- name: GetMsisdnPrefixGroupByReference :one
SELECT id, name, description, reference, created_at, updated_at FROM msisdn_prefix_groups
WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetMsisdnPrefixGroupByReference(ctx context.Context, reference *string) (MsisdnPrefixGroup, error) {
	row := q.db.QueryRow(ctx, getMsisdnPrefixGroupByReference, reference)
	var i MsisdnPrefixGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoutingAssignmentByID = `-- name: GetRoutingAssignmentByID :one
SELECT
    ra.id, ra.routing_group_id, ra.msisdn_prefix_group_id, ra.mno_id, ra.status, ra.priority, ra.comment, ra.created_at, ra.updated_at,
    rg.name as routing_group_name,
    rg.reference as routing_group_reference,
    mpg.name as prefix_group_name,
    mpg.reference as prefix_group_reference,
    m.name as mno_name
FROM routing_assignments ra
JOIN routing_groups rg ON ra.routing_group_id = rg.id
JOIN msisdn_prefix_groups mpg ON ra.msisdn_prefix_group_id = mpg.id
JOIN mnos m ON ra.mno_id = m.id
WHERE ra.id = $1 LIMIT 1
`

type GetRoutingAssignmentByIDRow struct {
	ID                    int32              `json:"id"`
	RoutingGroupID        int32              `json:"routingGroupId"`
	MsisdnPrefixGroupID   int32              `json:"msisdnPrefixGroupId"`
	MnoID                 int32              `json:"mnoId"`
	Status                string             `json:"status"`
	Priority              int32              `json:"priority"`
	Comment               *string            `json:"comment"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
	RoutingGroupName      string             `json:"routingGroupName"`
	RoutingGroupReference *string            `json:"routingGroupReference"`
	PrefixGroupName       string             `json:"prefixGroupName"`
	PrefixGroupReference  *string            `json:"prefixGroupReference"`
	MnoName               string             `json:"mnoName"`
}

func (q *Queries) GetRoutingAssignmentByID(ctx context.Context, id int32) (GetRoutingAssignmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoutingAssignmentByID, id)
	var i GetRoutingAssignmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoutingGroupID,
		&i.MsisdnPrefixGroupID,
		&i.MnoID,
		&i.Status,
		&i.Priority,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoutingGroupName,
		&i.RoutingGroupReference,
		&i.PrefixGroupName,
		&i.PrefixGroupReference,
		&i.MnoName,
	)
	return i, err
}

const getRoutingAssignmentByRoutingGroupAndPrefixGroup = `-- name: GetRoutingAssignmentByRoutingGroupAndPrefixGroup :one
SELECT ra.id, ra.routing_group_id, ra.msisdn_prefix_group_id, ra.mno_id, ra.status, ra.priority, ra.comment, ra.created_at, ra.updated_at
FROM routing_assignments ra
WHERE ra.routing_group_id = $1 AND ra.msisdn_prefix_group_id = $2
LIMIT 1
`

type GetRoutingAssignmentByRoutingGroupAndPrefixGroupParams struct {
	RoutingGroupID      int32 `json:"routingGroupId"`
	MsisdnPrefixGroupID int32 `json:"msisdnPrefixGroupId"`
}

func (q *Queries) GetRoutingAssignmentByRoutingGroupAndPrefixGroup(ctx context.Context, arg GetRoutingAssignmentByRoutingGroupAndPrefixGroupParams) (RoutingAssignment, error) {
	row := q.db.QueryRow(ctx, getRoutingAssignmentByRoutingGroupAndPrefixGroup, arg.RoutingGroupID, arg.MsisdnPrefixGroupID)
	var i RoutingAssignment
	err := row.Scan(
		&i.ID,
		&i.RoutingGroupID,
		&i.MsisdnPrefixGroupID,
		&i.MnoID,
		&i.Status,
		&i.Priority,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoutingGroupByID = `-- name: GetRoutingGroupByID :one
SELECT id, name, description, reference, created_at, updated_at FROM routing_groups
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoutingGroupByID(ctx context.Context, id int32) (RoutingGroup, error) {
	row := q.db.QueryRow(ctx, getRoutingGroupByID, id)
	var i RoutingGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoutingGroupByReference = `-- name: GetRoutingGroupByReference :one
SELECT id, name, description, reference, created_at, updated_at FROM routing_groups
WHERE reference = $1 LIMIT 1
`

func (q *Queries) GetRoutingGroupByReference(ctx context.Context, reference *string) (RoutingGroup, error) {
	row := q.db.QueryRow(ctx, getRoutingGroupByReference, reference)
	var i RoutingGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoutingGroupIdForSpCredential = `-- name: GetRoutingGroupIdForSpCredential :one
SELECT id as sp_credential_id, routing_group_id
FROM sp_credentials
WHERE id = $1
`

type GetRoutingGroupIdForSpCredentialRow struct {
	SpCredentialID int32  `json:"spCredentialId"`
	RoutingGroupID *int32 `json:"routingGroupId"`
}

// Returns the routing_group_id (can be NULL) and the sp_credential_id itself for context.
func (q *Queries) GetRoutingGroupIdForSpCredential(ctx context.Context, id int32) (GetRoutingGroupIdForSpCredentialRow, error) {
	row := q.db.QueryRow(ctx, getRoutingGroupIdForSpCredential, id)
	var i GetRoutingGroupIdForSpCredentialRow
	err := row.Scan(&i.SpCredentialID, &i.RoutingGroupID)
	return i, err
}

const getRoutingGroupReferenceById = `-- name: GetRoutingGroupReferenceById :one
SELECT reference FROM routing_groups WHERE id = $1
`

func (q *Queries) GetRoutingGroupReferenceById(ctx context.Context, id int32) (*string, error) {
	row := q.db.QueryRow(ctx, getRoutingGroupReferenceById, id)
	var reference *string
	err := row.Scan(&reference)
	return reference, err
}

const getSpCredentialRoutingGroupId = `-- name: GetSpCredentialRoutingGroupId :one
SELECT routing_group_id FROM sp_credentials WHERE id = $1
`

func (q *Queries) GetSpCredentialRoutingGroupId(ctx context.Context, id int32) (*int32, error) {
	row := q.db.QueryRow(ctx, getSpCredentialRoutingGroupId, id)
	var routing_group_id *int32
	err := row.Scan(&routing_group_id)
	return routing_group_id, err
}

const listMsisdnPrefixEntriesByGroup = `-- name: ListMsisdnPrefixEntriesByGroup :many
SELECT mpe.id, mpe.msisdn_prefix_group_id, mpe.msisdn_prefix, mpe.created_at, mpe.updated_at
FROM msisdn_prefix_entries mpe
WHERE mpe.msisdn_prefix_group_id = $1
ORDER BY mpe.msisdn_prefix
LIMIT $3 OFFSET $2
`

type ListMsisdnPrefixEntriesByGroupParams struct {
	MsisdnPrefixGroupID int32  `json:"msisdnPrefixGroupId"`
	Offset              *int32 `json:"offset"`
	Limit               *int32 `json:"limit"`
}

func (q *Queries) ListMsisdnPrefixEntriesByGroup(ctx context.Context, arg ListMsisdnPrefixEntriesByGroupParams) ([]MsisdnPrefixEntry, error) {
	rows, err := q.db.Query(ctx, listMsisdnPrefixEntriesByGroup, arg.MsisdnPrefixGroupID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MsisdnPrefixEntry
	for rows.Next() {
		var i MsisdnPrefixEntry
		if err := rows.Scan(
			&i.ID,
			&i.MsisdnPrefixGroupID,
			&i.MsisdnPrefix,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMsisdnPrefixGroups = `-- name: ListMsisdnPrefixGroups :many
SELECT id, name, description, reference, created_at, updated_at FROM msisdn_prefix_groups
ORDER BY name
LIMIT $2 OFFSET $1
`

type ListMsisdnPrefixGroupsParams struct {
	Offset *int32 `json:"offset"`
	Limit  *int32 `json:"limit"`
}

func (q *Queries) ListMsisdnPrefixGroups(ctx context.Context, arg ListMsisdnPrefixGroupsParams) ([]MsisdnPrefixGroup, error) {
	rows, err := q.db.Query(ctx, listMsisdnPrefixGroups, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MsisdnPrefixGroup
	for rows.Next() {
		var i MsisdnPrefixGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Reference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutingAssignmentsByRoutingGroup = `-- name: ListRoutingAssignmentsByRoutingGroup :many
SELECT
    ra.id, ra.routing_group_id, ra.msisdn_prefix_group_id, ra.mno_id, ra.status, ra.priority, ra.comment, ra.created_at, ra.updated_at,
    mpg.name as prefix_group_name,
    mpg.reference as prefix_group_reference,
    m.name as mno_name
FROM routing_assignments ra
JOIN msisdn_prefix_groups mpg ON ra.msisdn_prefix_group_id = mpg.id
JOIN mnos m ON ra.mno_id = m.id
WHERE ra.routing_group_id = $1
ORDER BY ra.priority ASC, mpg.name ASC
LIMIT $3 OFFSET $2
`

type ListRoutingAssignmentsByRoutingGroupParams struct {
	RoutingGroupID int32  `json:"routingGroupId"`
	Offset         *int32 `json:"offset"`
	Limit          *int32 `json:"limit"`
}

type ListRoutingAssignmentsByRoutingGroupRow struct {
	ID                   int32              `json:"id"`
	RoutingGroupID       int32              `json:"routingGroupId"`
	MsisdnPrefixGroupID  int32              `json:"msisdnPrefixGroupId"`
	MnoID                int32              `json:"mnoId"`
	Status               string             `json:"status"`
	Priority             int32              `json:"priority"`
	Comment              *string            `json:"comment"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt            pgtype.Timestamptz `json:"updatedAt"`
	PrefixGroupName      string             `json:"prefixGroupName"`
	PrefixGroupReference *string            `json:"prefixGroupReference"`
	MnoName              string             `json:"mnoName"`
}

// Lists assignments for a specific routing group.
func (q *Queries) ListRoutingAssignmentsByRoutingGroup(ctx context.Context, arg ListRoutingAssignmentsByRoutingGroupParams) ([]ListRoutingAssignmentsByRoutingGroupRow, error) {
	rows, err := q.db.Query(ctx, listRoutingAssignmentsByRoutingGroup, arg.RoutingGroupID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoutingAssignmentsByRoutingGroupRow
	for rows.Next() {
		var i ListRoutingAssignmentsByRoutingGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.RoutingGroupID,
			&i.MsisdnPrefixGroupID,
			&i.MnoID,
			&i.Status,
			&i.Priority,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixGroupName,
			&i.PrefixGroupReference,
			&i.MnoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutingGroups = `-- name: ListRoutingGroups :many
SELECT id, name, description, reference, created_at, updated_at FROM routing_groups
ORDER BY name
LIMIT $2 OFFSET $1
`

type ListRoutingGroupsParams struct {
	Offset *int32 `json:"offset"`
	Limit  *int32 `json:"limit"`
}

func (q *Queries) ListRoutingGroups(ctx context.Context, arg ListRoutingGroupsParams) ([]RoutingGroup, error) {
	rows, err := q.db.Query(ctx, listRoutingGroups, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoutingGroup
	for rows.Next() {
		var i RoutingGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Reference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoutingGroupFromSpCredential = `-- name: RemoveRoutingGroupFromSpCredential :one
UPDATE sp_credentials
SET routing_group_id = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, service_provider_id, protocol, status, system_id, password_hash, bind_type, api_key_hash, api_key_identifier, http_config, created_at, updated_at, routing_group_id
`

func (q *Queries) RemoveRoutingGroupFromSpCredential(ctx context.Context, spCredentialID int32) (SpCredential, error) {
	row := q.db.QueryRow(ctx, removeRoutingGroupFromSpCredential, spCredentialID)
	var i SpCredential
	err := row.Scan(
		&i.ID,
		&i.ServiceProviderID,
		&i.Protocol,
		&i.Status,
		&i.SystemID,
		&i.PasswordHash,
		&i.BindType,
		&i.ApiKeyHash,
		&i.ApiKeyIdentifier,
		&i.HttpConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoutingGroupID,
	)
	return i, err
}

const updateMsisdnPrefixEntry = `-- name: UpdateMsisdnPrefixEntry :one
UPDATE msisdn_prefix_entries
SET
    msisdn_prefix = COALESCE($1, msisdn_prefix),
    -- msisdn_prefix_group_id = COALESCE(sqlc.narg(msisdn_prefix_group_id), msisdn_prefix_group_id), -- Typically you wouldn't change the group_id, but delete and recreate
    updated_at = NOW()
WHERE id = $2
RETURNING id, msisdn_prefix_group_id, msisdn_prefix, created_at, updated_at
`

type UpdateMsisdnPrefixEntryParams struct {
	MsisdnPrefix *string `json:"msisdnPrefix"`
	ID           int32   `json:"id"`
}

func (q *Queries) UpdateMsisdnPrefixEntry(ctx context.Context, arg UpdateMsisdnPrefixEntryParams) (MsisdnPrefixEntry, error) {
	row := q.db.QueryRow(ctx, updateMsisdnPrefixEntry, arg.MsisdnPrefix, arg.ID)
	var i MsisdnPrefixEntry
	err := row.Scan(
		&i.ID,
		&i.MsisdnPrefixGroupID,
		&i.MsisdnPrefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMsisdnPrefixGroup = `-- name: UpdateMsisdnPrefixGroup :one
UPDATE msisdn_prefix_groups
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    reference = COALESCE($3, reference),
    updated_at = NOW()
WHERE id = $4
RETURNING id, name, description, reference, created_at, updated_at
`

type UpdateMsisdnPrefixGroupParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Reference   *string `json:"reference"`
	ID          int32   `json:"id"`
}

func (q *Queries) UpdateMsisdnPrefixGroup(ctx context.Context, arg UpdateMsisdnPrefixGroupParams) (MsisdnPrefixGroup, error) {
	row := q.db.QueryRow(ctx, updateMsisdnPrefixGroup,
		arg.Name,
		arg.Description,
		arg.Reference,
		arg.ID,
	)
	var i MsisdnPrefixGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoutingAssignment = `-- name: UpdateRoutingAssignment :one
UPDATE routing_assignments
SET
    -- routing_group_id = COALESCE(sqlc.narg(routing_group_id), routing_group_id), -- Usually not changed, delete/recreate
    -- msisdn_prefix_group_id = COALESCE(sqlc.narg(msisdn_prefix_group_id), msisdn_prefix_group_id), -- Usually not changed
    mno_id = COALESCE($1, mno_id),
    status = COALESCE($2, status),
    priority = COALESCE($3, priority),
    comment = COALESCE($4, comment),
    updated_at = NOW()
WHERE id = $5
RETURNING id, routing_group_id, msisdn_prefix_group_id, mno_id, status, priority, comment, created_at, updated_at
`

type UpdateRoutingAssignmentParams struct {
	MnoID    *int32  `json:"mnoId"`
	Status   *string `json:"status"`
	Priority *int32  `json:"priority"`
	Comment  *string `json:"comment"`
	ID       int32   `json:"id"`
}

// Can also add routing_group_id to WHERE if updates are always scoped to a group passed in context
// WHERE id = sqlc.arg(id) AND routing_group_id = sqlc.arg(routing_group_id_context)
func (q *Queries) UpdateRoutingAssignment(ctx context.Context, arg UpdateRoutingAssignmentParams) (RoutingAssignment, error) {
	row := q.db.QueryRow(ctx, updateRoutingAssignment,
		arg.MnoID,
		arg.Status,
		arg.Priority,
		arg.Comment,
		arg.ID,
	)
	var i RoutingAssignment
	err := row.Scan(
		&i.ID,
		&i.RoutingGroupID,
		&i.MsisdnPrefixGroupID,
		&i.MnoID,
		&i.Status,
		&i.Priority,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoutingGroup = `-- name: UpdateRoutingGroup :one
UPDATE routing_groups
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    reference = COALESCE($3, reference),
    updated_at = NOW()
WHERE id = $4
RETURNING id, name, description, reference, created_at, updated_at
`

type UpdateRoutingGroupParams struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Reference   *string `json:"reference"`
	ID          int32   `json:"id"`
}

func (q *Queries) UpdateRoutingGroup(ctx context.Context, arg UpdateRoutingGroupParams) (RoutingGroup, error) {
	row := q.db.QueryRow(ctx, updateRoutingGroup,
		arg.Name,
		arg.Description,
		arg.Reference,
		arg.ID,
	)
	var i RoutingGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Reference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
