// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: routing.sql

package database

import (
	"context"
)

const getApplicableRoutingRule = `-- name: GetApplicableRoutingRule :one
SELECT mno_id
FROM routing_rules
WHERE $1 LIKE prefix || '%' -- Use LIKE for prefix matching (e.g., '234803...' LIKE '234803%')
ORDER BY length(prefix) DESC, priority ASC -- Match longest prefix first, then by priority
LIMIT 1
`

func (q *Queries) GetApplicableRoutingRule(ctx context.Context, prefix string) (int32, error) {
	row := q.db.QueryRow(ctx, getApplicableRoutingRule, prefix)
	var mno_id int32
	err := row.Scan(&mno_id)
	return mno_id, err
}
