// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: sender_id.sql

package database

import (
	"context"
)

const getTemplateContent = `-- name: GetTemplateContent :one
SELECT content
FROM templates
WHERE id = $1 AND status = 'active'
  AND (service_provider_id IS NULL OR service_provider_id = $2)
`

type GetTemplateContentParams struct {
	ID                int32  `json:"id"`
	ServiceProviderID *int32 `json:"serviceProviderId"`
}

func (q *Queries) GetTemplateContent(ctx context.Context, arg GetTemplateContentParams) (string, error) {
	row := q.db.QueryRow(ctx, getTemplateContent, arg.ID, arg.ServiceProviderID)
	var content string
	err := row.Scan(&content)
	return content, err
}

const validateSenderID = `-- name: ValidateSenderID :one
SELECT id
FROM sender_ids
WHERE service_provider_id = $1
  AND sender_id_string = $2
  AND status = 'approved'
LIMIT 1
`

type ValidateSenderIDParams struct {
	ServiceProviderID *int32 `json:"serviceProviderId"`
	SenderIDString    string `json:"senderIdString"`
}

func (q *Queries) ValidateSenderID(ctx context.Context, arg ValidateSenderIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, validateSenderID, arg.ServiceProviderID, arg.SenderIDString)
	var id int32
	err := row.Scan(&id)
	return id, err
}
