// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: service_provider.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createSMPPCredential = `-- name: CreateSMPPCredential :one
INSERT INTO smpp_credentials (service_provider_id, system_id, password_hash, bind_type, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_provider_id, system_id, password_hash, bind_type, status, created_at, updated_at
`

type CreateSMPPCredentialParams struct {
	ServiceProviderID int32  `json:"serviceProviderId"`
	SystemID          string `json:"systemId"`
	PasswordHash      string `json:"passwordHash"`
	BindType          string `json:"bindType"`
	Status            string `json:"status"`
}

func (q *Queries) CreateSMPPCredential(ctx context.Context, arg CreateSMPPCredentialParams) (SmppCredential, error) {
	row := q.db.QueryRow(ctx, createSMPPCredential,
		arg.ServiceProviderID,
		arg.SystemID,
		arg.PasswordHash,
		arg.BindType,
		arg.Status,
	)
	var i SmppCredential
	err := row.Scan(
		&i.ID,
		&i.ServiceProviderID,
		&i.SystemID,
		&i.PasswordHash,
		&i.BindType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceProvider = `-- name: CreateServiceProvider :one
INSERT INTO service_providers (name, email, status)
VALUES ($1, $2, $3)
RETURNING id, name, email, status, created_at, updated_at
`

type CreateServiceProviderParams struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	Status string `json:"status"`
}

func (q *Queries) CreateServiceProvider(ctx context.Context, arg CreateServiceProviderParams) (ServiceProvider, error) {
	row := q.db.QueryRow(ctx, createServiceProvider, arg.Name, arg.Email, arg.Status)
	var i ServiceProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (service_provider_id, currency_code, balance, low_balance_threshold)
VALUES ($1, $2, $3, $4)
RETURNING id, service_provider_id, currency_code, balance, low_balance_threshold, low_balance_notified_at, created_at, updated_at
`

type CreateWalletParams struct {
	ServiceProviderID   int32           `json:"serviceProviderId"`
	CurrencyCode        string          `json:"currencyCode"`
	Balance             decimal.Decimal `json:"balance"`
	LowBalanceThreshold decimal.Decimal `json:"lowBalanceThreshold"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.ServiceProviderID,
		arg.CurrencyCode,
		arg.Balance,
		arg.LowBalanceThreshold,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.ServiceProviderID,
		&i.CurrencyCode,
		&i.Balance,
		&i.LowBalanceThreshold,
		&i.LowBalanceNotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSMPPCredentialBySystemID = `-- name: GetSMPPCredentialBySystemID :one
SELECT sp.id as service_provider_id, sp.name as service_provider_name, sc.id, sc.service_provider_id, sc.system_id, sc.password_hash, sc.bind_type, sc.status, sc.created_at, sc.updated_at
FROM smpp_credentials sc
JOIN service_providers sp ON sc.service_provider_id = sp.id
WHERE sc.system_id = $1 AND sc.status = 'active'
LIMIT 1
`

type GetSMPPCredentialBySystemIDRow struct {
	ServiceProviderID   int32              `json:"serviceProviderId"`
	ServiceProviderName string             `json:"serviceProviderName"`
	ID                  int32              `json:"id"`
	ServiceProviderID_2 int32              `json:"serviceProviderId2"`
	SystemID            string             `json:"systemId"`
	PasswordHash        string             `json:"passwordHash"`
	BindType            string             `json:"bindType"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt           pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetSMPPCredentialBySystemID(ctx context.Context, systemID string) (GetSMPPCredentialBySystemIDRow, error) {
	row := q.db.QueryRow(ctx, getSMPPCredentialBySystemID, systemID)
	var i GetSMPPCredentialBySystemIDRow
	err := row.Scan(
		&i.ServiceProviderID,
		&i.ServiceProviderName,
		&i.ID,
		&i.ServiceProviderID_2,
		&i.SystemID,
		&i.PasswordHash,
		&i.BindType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceProviderByID = `-- name: GetServiceProviderByID :one
SELECT id, name, email, status, created_at, updated_at FROM service_providers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetServiceProviderByID(ctx context.Context, id int32) (ServiceProvider, error) {
	row := q.db.QueryRow(ctx, getServiceProviderByID, id)
	var i ServiceProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
