// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: sp_credential.sql

package database

import (
	"context"
)

const getSPCredentialByAPIKey = `-- name: GetSPCredentialByAPIKey :one
SELECT
    spc.id,
    spc.service_provider_id,
    spc.protocol,
    spc.status,
    spc.api_key_hash,
    spc.http_config, -- Needed for callback URL?
    sp.default_currency_code
FROM sp_credentials spc
JOIN service_providers sp ON spc.service_provider_id = sp.id
WHERE spc.protocol = 'http'
  AND spc.api_key_hash = $1 -- Compare against the hashed key
  AND spc.status = 'active'
LIMIT 1
`

type GetSPCredentialByAPIKeyRow struct {
	ID                  int32   `json:"id"`
	ServiceProviderID   int32   `json:"serviceProviderId"`
	Protocol            string  `json:"protocol"`
	Status              string  `json:"status"`
	ApiKeyHash          *string `json:"apiKeyHash"`
	HttpConfig          []byte  `json:"httpConfig"`
	DefaultCurrencyCode string  `json:"defaultCurrencyCode"`
}

// Gets SP credential based on a hashed API key for HTTP auth.
func (q *Queries) GetSPCredentialByAPIKey(ctx context.Context, apiKeyHash *string) (GetSPCredentialByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getSPCredentialByAPIKey, apiKeyHash)
	var i GetSPCredentialByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.ServiceProviderID,
		&i.Protocol,
		&i.Status,
		&i.ApiKeyHash,
		&i.HttpConfig,
		&i.DefaultCurrencyCode,
	)
	return i, err
}

const getSPCredentialByKeyIdentifier = `-- name: GetSPCredentialByKeyIdentifier :one
SELECT
    spc.id,
    spc.service_provider_id,
    spc.protocol,
    spc.status,
    spc.api_key_hash, -- Need the HASH to compare against in Go
    spc.http_config,
    sp.default_currency_code
FROM sp_credentials spc
JOIN service_providers sp ON spc.service_provider_id = sp.id
WHERE spc.protocol = 'http'
  AND spc.api_key_identifier = $1 -- Lookup by IDENTIFIER
  AND spc.status = 'active'
LIMIT 1
`

type GetSPCredentialByKeyIdentifierRow struct {
	ID                  int32   `json:"id"`
	ServiceProviderID   int32   `json:"serviceProviderId"`
	Protocol            string  `json:"protocol"`
	Status              string  `json:"status"`
	ApiKeyHash          *string `json:"apiKeyHash"`
	HttpConfig          []byte  `json:"httpConfig"`
	DefaultCurrencyCode string  `json:"defaultCurrencyCode"`
}

// Gets SP credential based on a unique API key identifier for HTTP auth.
func (q *Queries) GetSPCredentialByKeyIdentifier(ctx context.Context, apiKeyIdentifier *string) (GetSPCredentialByKeyIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getSPCredentialByKeyIdentifier, apiKeyIdentifier)
	var i GetSPCredentialByKeyIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.ServiceProviderID,
		&i.Protocol,
		&i.Status,
		&i.ApiKeyHash,
		&i.HttpConfig,
		&i.DefaultCurrencyCode,
	)
	return i, err
}
